# This is the configuration file for Rio,
# an easy to use app & web framework for Python.

[app]
app_type = "website"  # This is either "website" or "app"
main_module = "testing.pages.main_page"  # The name of your Python module
